Repository project-lyrics/app-Android, pull requests merged in 2025-09, with the labels that each got.

#4 SCRUM-211 feature: collapsible artist topbar
  app/src/main/java/com/lyrics/feelin/core/designsystem/component/FeelinTopAppBar.kt
  app/src/main/java/com/lyrics/feelin/core/designsystem/icon/Icons.kt
  app/src/main/java/com/lyrics/feelin/navigation/FeelinNavHost.kt
  app/src/main/java/com/lyrics/feelin/presentation/view/community/CommunityMainScreen.kt
  app/src/main/java/com/lyrics/feelin/presentation/view/community/CommunityViewModel.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_notification.xml
Labels: feat, design

#5 SCRUM-235 fix: fix fab overlap with bottombar
  app/src/main/java/com/lyrics/feelin/navigation/FeelinNavHost.kt
Labels: bug

#7 SCRUM-238 refactor/ci: apply detekt, ktlint
  .cursor/rules/android-kotlin-detekt.mdc
  .cursor/rules/code-quality-workflow.mdc
  .cursor/rules/compose-guidelines.mdc
  .github/workflows/android-ci.yml
  agents.md
  app/build.gradle.kts
  app/detekt.yml
  app/src/main/java/com/lyrics/feelin/core/designsystem/component/FeelinTopAppBar.kt
  app/src/main/java/com/lyrics/feelin/core/designsystem/component/Navigation.kt
  app/src/main/java/com/lyrics/feelin/navigation/FeelinNavHost.kt
  app/src/main/java/com/lyrics/feelin/presentation/designsystem/theme/Color.kt
  app/src/main/java/com/lyrics/feelin/presentation/designsystem/theme/Theme.kt
  app/src/main/java/com/lyrics/feelin/presentation/designsystem/theme/Type.kt
  app/src/main/java/com/lyrics/feelin/presentation/view/community/CommunityMainScreen.kt
  app/src/main/java/com/lyrics/feelin/presentation/view/community/CommunityViewModel.kt
  app/src/main/java/com/lyrics/feelin/presentation/view/community/CommunityViewState.kt
  app/src/main/java/com/lyrics/feelin/presentation/view/component/note/NoteComponent.kt
  app/src/main/java/com/lyrics/feelin/presentation/view/component/note/NoteComponentData.kt
  app/src/main/java/com/lyrics/feelin/presentation/view/mypage/MyPageScreen.kt
  app/src/main/java/com/lyrics/feelin/presentation/view/note/NoteSearchScreen.kt
  app/src/main/java/com/lyrics/feelin/util/LocalDateTimeExtension.kt
  app/src/test/java/com/lyrics/feelin/ExampleUnitTest.kt
  claude.md
  gradle/libs.versions.toml
Labels: refactor, ci
